### DISCUSSION TITLE
videos/css/flex-layout/

### DISCUSSION THREAD

**Discussion by giscus** [zxuqian/zxuqian.cn#51] [Announcements]
# videos/css/flex-layout/

CSS Flex 布局 2分钟动画快速掌握。

https://zxuqian.cn/videos/css/flex-layout/

**Comment by zxuqian** [comment]
你学会了吗？

**Reply by hxer520** [reply]
请问下您的博客里面文章的markdown的H2的样式该如何实现呢?小问题,但困扰好久了,爱好者前端不太明白

**Reply by zxuqian** [reply]
可以用 Chrome 开发者工具看源码哈。具体是这样的：

2 级标题用的 h2 元素。

下划线是通过 `border-bottom` 设置的：
```css
h2 {
    border-bottom: 1px solid #338bff;
}
```
左边的竖线，是用了一个 `before` 伪元素添加的，伪元素必须有 content 属性才能显示，并且有宽度，这里随便给了它一个 "." 号，然后把它的颜色设置成透明的，隐藏，最后把整个伪元素的背景 `background` 设置成想要的颜色就行了：
```css
h2:before {
    background: #338bff;
    color: transparent;
    content: ".";
    display: inline-block;
    margin-right: 0.4em;
}
```
